####################################
# Assignment No. : 4
# Date: 00/09/2025
# Name: Bishnu Prasad Baruah
# Roll No. : 256121007
# Email: b.baruah@iitg.ac.in
#####################################

In [7]:
import numpy as np
np.set_printoptions(legacy='1.13')
matrix_A = np.array([[4,1,2],
                     [1,3,0],
                     [2,0,5]], dtype = float)

In [8]:
v1 = np.array([[1],[1],[1]])             #==========initial guess vector

In [9]:
def power(a,b,c):                        #==========a = matrix, b = initial guess, c = tolerance
    
    A = np.copy(a)
    q_0 = (b)/(np.linalg.norm(b))
    
    z_k = np.matmul(A,q_0)               ##===========Finding the new vector
    q_k = (z_k)/(np.linalg.norm(z_k))    ##===========Normalizing the new vector
    
    for i in range(len(q_k)):
        stop = (abs(q_k[i] - q_0[i])/abs(q_k[i]))    #===========stop check
    
    while stop > c:
        
        z_k = np.matmul(A,q_0)
        q_k = (z_k)/(np.linalg.norm(z_k))    #Finding the next vector
        
        #==================stop check=================
        stop = 0
        for i in range(len(q_k)):
            stop += (abs(q_k[i] - q_0[i])/abs(q_k[i]))

        if stop <= c:
            break
        #=============================================
        
        q_0 = q_k
        
    e = np.matmul((q_0.T),(np.matmul(A,q_0)))    #eigen value calculation
    
    return q_0,e

In [10]:
dominant_vector,dominant_eigen_value = power(matrix_A,v1,1.0e-10)

In [11]:
dominant_vector

array([[ 0.63117897],
       [ 0.17202654],
       [ 0.75632002]])

In [12]:
dominant_eigen_value

array([[ 6.66907909]])

## Inverse power method

In [13]:
#finding inverse using LU decomposition

In [14]:
##===----------inverse matrix creation==========
def inverse(m):
    A = np.copy(m)
    n = len(A)

    ####-============--UPPER TRIANGULAR-&-LOWER TRIANGULAR=============-####
    L = np.identity(n)  ##-----------identity matrix------------###
    
    for k in range(n-1): #row iteration
        for i in range(k+1,n): #column iteration
            factor = (A[i][k])/(A[k][k])
            
            L[i][k] = factor   
            for j in range(n):  #all column iteration
                A[i][j] = A[i][j] - factor*A[k][j]  #i = row, j = column
    U = A
    #return L,U
    ###=====================================================###


    
    inv = np.zeros((n,n),dtype = float)  ##---==EMPTY INVERSE MATRIX----

    ##---Creation of a matrix that contains columns of identity matrix as elements
    v = []
    matrix = np.identity(n)
    for i in range(n):
        B = np.reshape(matrix[:,i],(n,1))
        v.append(B)
    BB =  v   
    #======-------------------===================-----------------==========
    
    for k in range(n):     
        B = BB[k]      ##-<<==----====== SELECT A NEW COLUMN FOR EACH K ====---###
        
        ##----===========CREATION OF D MATRIX FOR EACH COLUMN==============----##
        D = np.zeros((n,1),dtype = float)
        count = 0
        for i in range(n):
            dog = B[i]
            if count >0:
                cat = 0
                for j in range(i):
                    cat = cat + L[i][j]*D[j]
                    #print(cat)
                dog = B[i] - cat
            D[i] = dog
            count = count + 1
        ##----========----====================================------=====----##

        
        ##----======CREATION OF COLUMN OF INVERSE MATRIX--USING---UX=D---====###
        #===========-----------backward_substitution(U,D)
        a,b = np.copy(U), np.copy(D)
        n=len(a)
        x = np.zeros((n,1), dtype = float)
        x[n-1] = (b[n-1])/(a[n-1][n-1])
        for i in range(n-2,-1,-1):
            sum = b[i]
            for j in range(i+1,n):
                sum = sum - a[i][j]*x[j]
            x[i] = sum/a[i][i]
        third =  x
        ##----========----=====================================------=====----##

        
        inv[:,k] = third.T   #[:,2] == : means all rows, column 2 => all rows of coumn 2
    return inv            # since it select all rows of a particular column, the input must be a row matrix to replace the 
                                 #elements of that column ==> so taking transpose


In [27]:
B = inverse(matrix_A)
B

array([[ 0.34883721, -0.11627907, -0.13953488],
       [-0.11627907,  0.37209302,  0.04651163],
       [-0.13953488,  0.04651163,  0.25581395]])

In [16]:
eigen_vector, dominant_eigen_value_B = power(B,v1,1e-20)
smallest_eigen_value = 1/(dominant_eigen_value_B)

smallest_eigen_value

array([[ 1.85489731]])

In [17]:
eigen_vector

array([[-0.67931306],
       [ 0.59323331],
       [ 0.43198148]])

In [18]:
#1. first do the LU decomposition of A 
#2. LY = q_0 | find Y 
#3. UZ_k = Y | use backward substitution to find Z_k 
#4. q_k = normalization of Z_k 

In [19]:
def L_U_decomp(c):
    A = np.copy(c)
    n = len(A)
    
    ####-============--UPPER TRIANGULAR-&-LOWER TRIANGULAR=============-####
    L = np.identity(n)  ##-----------identity matrix------------###
    
    for k in range(n-1): #row iteration
        for i in range(k+1,n): #column iteration
            factor = (A[i][k])/(A[k][k])
            
            L[i][k] = factor   
            for j in range(n):  #all column iteration
                A[i][j] = A[i][j] - factor*A[k][j]  #i = row, j = column
    U = A
    return L,U


In [20]:
def forwardsubs(a,b):  ##---Ly=B------
    L = np.copy(a)
    B = np.copy(b)
    n = len(L)
    y = np.zeros((n,1),dtype = float)
    count = 0
    for i in range(n):
        dog = B[i]
        if count >0:
            cat = 0
            for j in range(i):
                cat = cat + L[i][j]*y[j]
                #print(cat)
            dog = B[i] - cat
        y[i] = dog
        count = count + 1
    return y

In [21]:
##--========--- USE OF UX=D TO EVALUATE X-----==========##
def backward_substitution(c,d):
    a,b = np.copy(c), np.copy(d)
    n=len(a)
    x = np.zeros((n,1), dtype = float)
    x[n-1] = (b[n-1])/(a[n-1][n-1])
    for i in range(n-2,-1,-1):
        sum = b[i]
        for j in range(i+1,n):
            sum = sum - a[i][j]*x[j]
        x[i] = sum/a[i][i]
    return x



In [22]:
def inv_power(a,b,tol):
    A,v = np.copy(a), np.copy(b)

    L,U = L_U_decomp(A)
    q_0 = (v)/(np.linalg.norm(v))

    y = forwardsubs(L,q_0)
    z = backward_substitution(U,y)

    q_k = (z)/(np.linalg.norm(z))
    
    stop = 0
    for i in range(len(q_k)):
        stop += (abs(q_k[i] - q_0[i])/abs(q_k[i]))

    while stop > tol:
        y = forwardsubs(L,q_0)
        z = backward_substitution(U,y)

        q_k = (z)/(np.linalg.norm(z))

        stop = 0
        for i in range(len(q_k)):
            stop += (abs(q_k[i] - q_0[i])/abs(q_k[i]))

        if stop <= tol:
            break

        q_0 = q_k
        
    e = np.matmul((q_0.T),(np.matmul(A,q_0)))    #eigen value calculation
    #lam = np.matmul(q_0.T, z)
    #e = 1.0 / lam
    return q_0,e

In [24]:
vector,value = inv_power(matrix_A,v1,1.0e-10)

In [25]:
vector

array([[-0.67931306],
       [ 0.59323331],
       [ 0.43198148]])

In [26]:
value

array([[ 1.85489731]])