####################################
# Assignment No. : 3
# Date: 00/09/2025
# Name: Bishnu Prasad BAruah
# Roll No. : 256121007
# Email: b.baruah@iitg.ac.in
#####################################

In [3]:
import numpy as np
mat_a = np.array([[3,-0.1,-0.2],
              [0.1,7,-0.3],
              [0.3,-0.2,10]], dtype=float)
mat_b = np.array([[7.85],
              [-19.3],
              [71.4]], dtype = float)

## QUESTION #1

In [4]:
def naive_gauss(c,d):
    a,b = np.copy(c) , np.copy(d)
    
    ## -------FORWARD ELEMINATION ---###
    n = len(a)
    for k in range(n-1):
        for i in range(k+1,n):
            factor = (a[i][k])/(a[k][k])
            for j in range(n):
                a[i][j] = a[i][j] - factor*a[k][j]
            b[i] = b[i] - b[k]*factor

    ## --------------------------------##
    
    ## -------BACKWARD SUBSTITUTION ---###
    x = np.zeros((n,1), dtype = float)
    x[n-1] = (b[n-1])/(a[n-1][n-1])
    for i in range(n-2,-1,-1):
        sum = b[i]
        for j in range(i+1,n):
            sum = sum - a[i][j]*x[j]
        x[i] = sum/a[i][i]
    ##-----------------------------------##
    return x

In [5]:
result = naive_gauss(mat_a,mat_b)
result

array([[ 3. ],
       [-2.5],
       [ 7. ]])

## QUESTION #2

In [6]:
def L_U_decomp(c):
    A = np.copy(c)
    n = len(A)
    
    ####-============--UPPER TRIANGULAR-&-LOWER TRIANGULAR=============-####
    L = np.identity(n)  ##-----------identity matrix------------###
    
    for k in range(n-1): #row iteration
        for i in range(k+1,n): #column iteration
            factor = (A[i][k])/(A[k][k])
            
            L[i][k] = factor   
            for j in range(n):  #all column iteration
                A[i][j] = A[i][j] - factor*A[k][j]  #i = row, j = column
    U = A
    return L,U
    ###=====================================================###

In [7]:
L, U = L_U_decomp(mat_a)

In [8]:
def forwardsubs(a,b):  ##---LD=B------Finding D  matrix
    L = np.copy(a)
    B = np.copy(b)
    n = len(L)
    D = np.zeros((n,1),dtype = float)
    count = 0
    for i in range(n):
        dog = B[i]
        if count >0:
            cat = 0
            for j in range(i):
                cat = cat + L[i][j]*D[j]
                #print(cat)
            dog = B[i] - cat
        D[i] = dog
        count = count + 1
    return D

In [9]:
D = forwardsubs(L,mat_b)

In [10]:
##--========--- USE OF UX=D TO EVALUATE X-----==========##
def backward_substitution(c,d):
    a,b = np.copy(c), np.copy(d)
    n=len(a)
    x = np.zeros((n,1), dtype = float)
    x[n-1] = (b[n-1])/(a[n-1][n-1])
    for i in range(n-2,-1,-1):
        sum = b[i]
        for j in range(i+1,n):
            sum = sum - a[i][j]*x[j]
        x[i] = sum/a[i][i]
    return x

In [11]:
backward_substitution(U,D)

array([[ 3. ],
       [-2.5],
       [ 7. ]])

## INVERSE MATRIX CALCULATION

In [12]:
##===----------inverse matrix creation==========
def inverse(m):
    A = np.copy(m)
    n = len(A)

    ####-============--UPPER TRIANGULAR-&-LOWER TRIANGULAR=============-####
    L = np.identity(n)  ##-----------identity matrix------------###
    
    for k in range(n-1): #row iteration
        for i in range(k+1,n): #column iteration
            factor = (A[i][k])/(A[k][k])
            
            L[i][k] = factor   
            for j in range(n):  #all column iteration
                A[i][j] = A[i][j] - factor*A[k][j]  #i = row, j = column
    U = A
    #return L,U
    ###=====================================================###


    
    inv = np.zeros((n,n),dtype = float)  ##---==EMPTY INVERSE MATRIX----

    ##---Creation of a matrix that contains columns of identity matrix as elements
    v = []
    matrix = np.identity(n)
    for i in range(n):
        B = np.reshape(matrix[:,i],(n,1))
        v.append(B)
    BB =  v   
    #======-------------------===================-----------------==========
    
    for k in range(n):     
        B = BB[k]      ##-<<==----====== SELECT A NEW COLUMN FOR EACH K ====---###
        
        ##----===========CREATION OF D MATRIX FOR EACH COLUMN==============----##
        D = np.zeros((n,1),dtype = float)
        count = 0
        for i in range(n):
            dog = B[i]
            if count >0:
                cat = 0
                for j in range(i):
                    cat = cat + L[i][j]*D[j]
                    #print(cat)
                dog = B[i] - cat
            D[i] = dog
            count = count + 1
        ##----========----====================================------=====----##

        
        ##----======CREATION OF COLUMN OF INVERSE MATRIX--USING---UX=D---====###
        #===========-----------backward_substitution(U,D)
        a,b = np.copy(U), np.copy(D)
        n=len(a)
        x = np.zeros((n,1), dtype = float)
        x[n-1] = (b[n-1])/(a[n-1][n-1])
        for i in range(n-2,-1,-1):
            sum = b[i]
            for j in range(i+1,n):
                sum = sum - a[i][j]*x[j]
            x[i] = sum/a[i][i]
        third =  x
        ##----========----=====================================------=====----##

        
        inv[:,k] = third.T   #[:,2] == : means all rows, column 2 => all rows of coumn 2
    return inv            # since it select all rows of a particular column, the input must be a row matrix to replace the 
                                 #elements of that column ==> so taking transpose


In [13]:
inverse(mat_a)

array([[ 0.33248872,  0.00494407,  0.0067981 ],
       [-0.00518177,  0.14290264,  0.00418344],
       [-0.0100783 ,  0.00270973,  0.09987973]])

In [14]:
##---===--CROSS-CHECK--USING--NUMPY----======###
np.linalg.inv(mat_a)
##---=======-------------========--===========###

array([[ 0.33248872,  0.00494407,  0.0067981 ],
       [-0.00518177,  0.14290264,  0.00418344],
       [-0.0100783 ,  0.00270973,  0.09987973]])